// Code generated by codegen/generate.py; DO NOT EDIT.


import { describe, test, expect } from "bun:test";
import {
  Client,
  newClient,
  ai21,
  anthropic,
  azure,
  bedrock,
  cerebras,
  cohere,
  deepseek,
  doubao,
  ernie,
  fireworks,
  google,
  grok,
  groq,
  jan,
  llamacpp,
  lmstudio,
  minimax,
  mistral,
  moonshot,
  ollama,
  openai,
  openrouter,
  perplexity,
  pixverse,
  qwen,
  recraft,
  sambanova,
  together,
  vertex,
  vidu,
  vllm,
  workersai,
  yi,
  zhipu,
} from "../src/builders/index.ts";

describe("Every per-provider factory constructs a Client", () => {
  test("every factory + newClient escape hatch", () => {
    const clients: Client[] = [
      newClient("ai21", "k"),
      ai21("k"),
      anthropic("k"),
      azure("k"),
      bedrock("k"),
      cerebras("k"),
      cohere("k"),
      deepseek("k"),
      doubao("k"),
      ernie("k"),
      fireworks("k"),
      google("k"),
      grok("k"),
      groq("k"),
      jan("k"),
      llamacpp("k"),
      lmstudio("k"),
      minimax("k"),
      mistral("k"),
      moonshot("k"),
      ollama("k"),
      openai("k"),
      openrouter("k"),
      perplexity("k"),
      pixverse("k"),
      qwen("k"),
      recraft("k"),
      sambanova("k"),
      together("k"),
      vertex("k"),
      vidu("k"),
      vllm("k"),
      workersai("k"),
      yi("k"),
      zhipu("k"),
    ];
    for (const c of clients) {
      expect(c).toBeInstanceOf(Client);
      expect(c.provider.apiKey).toBe("k");
    }
    expect(clients).toHaveLength(35);
  });
});
