// Code generated by codegen/generate.py; DO NOT EDIT.


import { describe, test, expect } from "bun:test";
import { generateImage } from "../src/llmkit.ts";
import { Providers } from "../src/providers/providers.ts";

describe("image integration \u2014 google gemini-3-pro-image-preview", () => {
  test.skipIf(!process.env.GOOGLE_API_KEY || !process.env.LLMKIT_RUN_SLOW_IMAGE)(
    "generates a 1x1 image with usage tokens",
    async () => {
      const resp = await generateImage(
        { name: Providers.google, apiKey: process.env.GOOGLE_API_KEY! },
        { prompt: "A simple red circle on a white background.", model: "gemini-3-pro-image-preview" },
        { aspectRatio: "1:1", imageSize: "1K" },
      );
      expect(resp.images.length).toBeGreaterThan(0);
      expect(resp.images[0]!.bytes.length).toBeGreaterThan(0);
      expect(resp.tokens.output).toBeGreaterThan(0);
    },
    60_000,
  );
});

describe("image integration \u2014 google gemini-3.1-flash-image-preview", () => {
  test.skipIf(!process.env.GOOGLE_API_KEY)(
    "generates a 1x1 image with usage tokens",
    async () => {
      const resp = await generateImage(
        { name: Providers.google, apiKey: process.env.GOOGLE_API_KEY! },
        { prompt: "A simple red circle on a white background.", model: "gemini-3.1-flash-image-preview" },
        { aspectRatio: "1:1", imageSize: "1K" },
      );
      expect(resp.images.length).toBeGreaterThan(0);
      expect(resp.images[0]!.bytes.length).toBeGreaterThan(0);
      expect(resp.tokens.output).toBeGreaterThan(0);
    },
    60_000,
  );
});

