// Code generated by codegen/generate.py; DO NOT EDIT.


export interface Usage {
  input: number;
  output: number;
  cacheWrite: number;
  cacheRead: number;
  reasoning: number;
  /**
   * cost is the provider-reported request cost in USD (ADR-027). Not a TokenDimension — a distinct monetary field. Only OpenRouter (the request must opt in with usage: {include: true}) and xAI report it. 0 is ambiguous: unreported or genuinely free — providers whose usageCostPath is empty never report cost.
   */
  cost: number;
}

export type MiddlewarePhase = "pre" | "post";

export type MiddlewareOp =
  | "llm_request"
  | "tool_call"
  | "cache_create"
  | "upload"
  | "batch_submit"
  | "image_generation"
  | "music_generation"
  | "models_list";

export interface Event {
  // Always set.
  op: MiddlewareOp;
  // Always set.
  phase: MiddlewarePhase;
  // Always set.
  provider: string;
  // Always set.
  model: string;
  // Only set when Op=tool_call.
  tool?: string;
  // Only set when Op=tool_call, Phase=pre. Mutation by middleware is observed by the tool.
  args?: Record<string, unknown>;
  // Only set when Op=tool_call, Phase=post.
  result?: string;
  // Set for Op=llm_request, Phase=post.
  usage?: Usage;
  // Set in Phase=post when the operation failed.
  err?: Error;
  // Set in Phase=post.
  duration?: number;
}

// Consumers supply their own Context shape; library treats it as opaque.
export type Context = unknown;

// MiddlewareFn is the user-supplied pre/post hook. Pre-phase non-null return
// vetoes the operation; post-phase return value is ignored.
export type MiddlewareFn = (ctx: Context, e: Event) => Error | null;
