// Code generated by codegen/generate.py; DO NOT EDIT.


export interface Usage {
  input: number;
  output: number;
  cacheCreation: number;
  cacheRead: number;
}

export type MiddlewarePhase = "pre" | "post";

export type MiddlewareOp =
  | "llm_request"
  | "tool_call"
  | "cache_create"
  | "upload"
  | "batch_submit";

export interface Event {
  // Always set.
  op: MiddlewareOp;
  // Always set.
  phase: MiddlewarePhase;
  // Always set.
  provider: string;
  // Always set.
  model: string;
  // Only set when Op=tool_call.
  tool?: string;
  // Only set when Op=tool_call, Phase=pre. Mutation by middleware is observed by the tool.
  args?: Record<string, unknown>;
  // Only set when Op=tool_call, Phase=post.
  result?: string;
  // Set for Op=llm_request, Phase=post.
  usage?: Usage;
  // Set in Phase=post when the operation failed.
  err?: Error;
  // Set in Phase=post.
  duration?: number;
}

// Consumers supply their own Context shape; library treats it as opaque.
export type Context = unknown;

// MiddlewareFn is the user-supplied pre/post hook. Pre-phase non-null return
// vetoes the operation; post-phase return value is ignored.
export type MiddlewareFn = (ctx: Context, e: Event) => Error | null;
