// Code generated by codegen/generate.py; DO NOT EDIT.

// Live-catalogue response parsers (ADR-019). Each function maps one
// provider wire shape to a typed ParsedModelsPage. Capabilities
// enrichment from the ontology table lives in models.ts — these parsers
// populate only wire-provided fields.

export interface ParsedModelRecord {
  id: string;
  displayName?: string;
  description?: string;
  created?: number;
  contextWindow?: number;
  maxOutput?: number;
  raw: unknown;
}

export interface ParsedModelsPage {
  records: ParsedModelRecord[];
  nextCursor: string;
}

/** Decode the cursor-paginated Anthropic /v1/models response. */
export function parseAnthropicModelsResponse(body: string): ParsedModelsPage {
  const envelope = JSON.parse(body) as {
    data?: Array<Record<string, unknown>>;
    has_more?: boolean;
    last_id?: string;
  };
  const data = envelope.data ?? [];
  const records: ParsedModelRecord[] = data.map((wire) => {
    const maxOut =
      (wire.max_output_tokens as number | undefined) ??
      (wire.max_tokens as number | undefined) ??
      0;
    const createdAt = wire.created_at as string | undefined;
    const created = createdAt ? Math.floor(new Date(createdAt).getTime() / 1000) || undefined : undefined;
    return {
      id: String(wire.id ?? ""),
      displayName: wire.display_name as string | undefined,
      contextWindow: wire.max_input_tokens as number | undefined,
      maxOutput: maxOut || undefined,
      created,
      raw: wire,
    };
  });
  const nextCursor = envelope.has_more && envelope.last_id ? envelope.last_id : "";
  return { records, nextCursor };
}

/** Decode the non-paginated OpenAI-cohort /v1/models response (also xAI,
 *  Cerebras, Groq, Together — every provider on the canonical OpenAI shape). */
export function parseOpenAICohortModelsResponse(body: string): ParsedModelsPage {
  const envelope = JSON.parse(body) as { data?: Array<Record<string, unknown>> };
  const data = envelope.data ?? [];
  const records: ParsedModelRecord[] = data.map((wire) => ({
    id: String(wire.id ?? ""),
    created: wire.created as number | undefined,
    raw: wire,
  }));
  return { records, nextCursor: "" };
}

/** Decode the cursor-paginated Google /v1beta/models response. Strips the
 *  "models/" prefix from each id so callers round-trip raw model IDs. */
export function parseGoogleModelsResponse(body: string): ParsedModelsPage {
  const envelope = JSON.parse(body) as {
    models?: Array<Record<string, unknown>>;
    nextPageToken?: string;
  };
  const data = envelope.models ?? [];
  const records: ParsedModelRecord[] = data.map((wire) => {
    let id = String(wire.name ?? "");
    const prefix = "models/";
    if (id.startsWith(prefix)) id = id.slice(prefix.length);
    return {
      id,
      displayName: wire.displayName as string | undefined,
      description: wire.description as string | undefined,
      contextWindow: wire.inputTokenLimit as number | undefined,
      maxOutput: wire.outputTokenLimit as number | undefined,
      raw: wire,
    };
  });
  return { records, nextCursor: envelope.nextPageToken ?? "" };
}
