// Code generated by codegen/generate.py; DO NOT EDIT.


import type { ProviderName } from "./providers.ts";

// Speech wire-shape discriminators. Each fully determines the request
// body and the response audio path.
export type SpeechWireShape = "SpeechInworld";

export interface SpeechModelDef {
  modelId: string;
  label: string;
  outputMime: string;
  /** ADR-037 advisory fact (queryable, never gated); 0 when unverified. */
  sampleRateHz: number;
}

export interface SpeechGenDef {
  wireShape: SpeechWireShape;
  // genEndpoint is an override; empty = use provider main endpoint.
  genEndpoint: string;
  // voices is the catalogue the Voice setter validates against.
  voices: string[];
  models: SpeechModelDef[];
}

const SPEECH_GEN: Partial<Record<ProviderName, SpeechGenDef>> = {
  inworld: {
    wireShape: "SpeechInworld",
    genEndpoint: "/tts/v1/voice",
    voices: ["Alex", "Ashley", "Dennis"],
    models: [
      {
        modelId: "inworld-tts-1.5-max",
        label: "Inworld TTS 1.5 Max",
        outputMime: "audio/wav",
        sampleRateHz: 0,
      },
      {
        modelId: "inworld-tts-1.5-mini",
        label: "Inworld TTS 1.5 Mini",
        outputMime: "audio/wav",
        sampleRateHz: 0,
      },
      {
        modelId: "inworld-tts-2",
        label: "Inworld TTS 2",
        outputMime: "audio/wav",
        sampleRateHz: 0,
      },
    ],
  },
};

export function speechGenConfig(provider: ProviderName): SpeechGenDef | undefined {
  return SPEECH_GEN[provider];
}
