// Code generated by codegen/generate.py; DO NOT EDIT.


import type { ProviderName } from "./providers.ts";

// Video wire-shape discriminators. Each selects the submit-body build,
// poll mechanism, and result-extraction transform.
export type VideoWireShape = "VideoGrok" | "VideoZhipu" | "VideoTogether";

// Output-delivery modes: download bytes | return URL | caller S3 URI.
export type VideoOutputDelivery = "DeliveryDownload" | "DeliveryURL" | "DeliveryOutputURI";

export interface VideoModelDef {
  modelId: string;
  label: string;
  supportsImageToVideo: boolean;
  maxDurationSeconds: number;
  outputMime: string;
  resolutions: string[];
}

export interface VideoGenDef {
  wireShape: VideoWireShape;
  outputDelivery: VideoOutputDelivery;
  // videoBaseUrl is the video API base when it differs from the chat base; "" = use chat base.
  videoBaseUrl: string;
  // genEndpoint is the submit endpoint path, relative to the resolved video base.
  genEndpoint: string;
  // pollEndpoint is the poll template with an {id}, relative to the resolved video base.
  pollEndpoint: string;
  // submitHandleField is a dotted path to the poll handle id.
  submitHandleField: string;
  requiresOutputUri: boolean;
  models: VideoModelDef[];
}

const VIDEO_GEN: Partial<Record<ProviderName, VideoGenDef>> = {
  grok: {
    wireShape: "VideoGrok",
    outputDelivery: "DeliveryURL",
    videoBaseUrl: "",
    genEndpoint: "/v1/videos/generations",
    pollEndpoint: "/v1/videos/{id}",
    submitHandleField: "request_id",
    requiresOutputUri: false,
    models: [
      {
        modelId: "grok-imagine-video",
        label: "Grok Imagine Video",
        supportsImageToVideo: true,
        maxDurationSeconds: 15,
        outputMime: "video/mp4",
        resolutions: ["480p", "720p"],
      },
    ],
  },
  together: {
    wireShape: "VideoTogether",
    outputDelivery: "DeliveryURL",
    videoBaseUrl: "",
    genEndpoint: "/v2/videos",
    pollEndpoint: "/v2/videos/{id}",
    submitHandleField: "id",
    requiresOutputUri: false,
    models: [
      {
        modelId: "minimax/video-01-director",
        label: "MiniMax Video 01 Director (Together)",
        supportsImageToVideo: true,
        maxDurationSeconds: 6,
        outputMime: "video/mp4",
        resolutions: ["720p"],
      },
    ],
  },
  zhipu: {
    wireShape: "VideoZhipu",
    outputDelivery: "DeliveryURL",
    videoBaseUrl: "",
    genEndpoint: "/v4/videos/generations",
    pollEndpoint: "/v4/async-result/{id}",
    submitHandleField: "id",
    requiresOutputUri: false,
    models: [
      {
        modelId: "cogvideox-3",
        label: "CogVideoX-3",
        supportsImageToVideo: true,
        maxDurationSeconds: 10,
        outputMime: "video/mp4",
        resolutions: ["1080p", "4k", "720p"],
      },
    ],
  },
};

export function videoGenConfig(provider: ProviderName): VideoGenDef | undefined {
  return VIDEO_GEN[provider];
}
