// Code generated by codegen/generate.py; DO NOT EDIT.


import type { ProviderName } from "./providers.ts";

// Video wire-shape discriminators. Each selects the submit-body build,
// poll mechanism, and result-extraction transform.
export type VideoWireShape = "VideoGrok" | "VideoZhipu";

// Output-delivery modes: download bytes | return URL | caller S3 URI.
export type VideoOutputDelivery = "DeliveryDownload" | "DeliveryURL" | "DeliveryOutputURI";

export interface VideoModelDef {
  modelId: string;
  label: string;
  supportsImageToVideo: boolean;
  maxDurationSeconds: number;
  outputMime: string;
  resolutions: string[];
}

export interface VideoGenDef {
  wireShape: VideoWireShape;
  outputDelivery: VideoOutputDelivery;
  // genEndpoint is the submit endpoint path.
  genEndpoint: string;
  requiresOutputUri: boolean;
  models: VideoModelDef[];
}

const VIDEO_GEN: Partial<Record<ProviderName, VideoGenDef>> = {
  grok: {
    wireShape: "VideoGrok",
    outputDelivery: "DeliveryURL",
    genEndpoint: "/v1/videos/generations",
    requiresOutputUri: false,
    models: [
      {
        modelId: "grok-imagine-video",
        label: "Grok Imagine Video",
        supportsImageToVideo: true,
        maxDurationSeconds: 15,
        outputMime: "video/mp4",
        resolutions: ["480p", "720p"],
      },
    ],
  },
  zhipu: {
    wireShape: "VideoZhipu",
    outputDelivery: "DeliveryURL",
    genEndpoint: "/v4/videos/generations",
    requiresOutputUri: false,
    models: [
      {
        modelId: "cogvideox-3",
        label: "CogVideoX-3",
        supportsImageToVideo: true,
        maxDurationSeconds: 10,
        outputMime: "video/mp4",
        resolutions: ["1080p", "4k", "720p"],
      },
    ],
  },
};

export function videoGenConfig(provider: ProviderName): VideoGenDef | undefined {
  return VIDEO_GEN[provider];
}
