// Code generated by codegen/generate.py; DO NOT EDIT.

// Typed-builder API surface introduced in ADR-009 / plan 016. Phase 2b
// emits skeleton classes + throwing terminals; phase 3 will hand-write a
// subset of terminals against the legacy free-function runtime in sibling
// files (text.ts, image.ts, agent.ts, upload.ts in this directory).
// Phase 4 will move the surface into the main llmkit module once the
// legacy functional API is deleted.

import type { File, Message, Response, Tool } from "../types.ts";
import type { ImageData, ImageResponse, Part } from "../image.ts";
import type { MiddlewareFn } from "../providers/middleware.ts";
import { BatchHandle } from "./batch.ts";

export type { File, Message, Response, Tool, ImageData, ImageResponse, Part, MiddlewareFn };
export { BatchHandle };

export interface ProviderConfig {
  name: string;
  apiKey: string;
  baseUrl?: string;
}

function clone<T extends object>(b: T): T {
  return Object.assign(Object.create(Object.getPrototypeOf(b)), b) as T;
}

import { agentPrompt, agentReset } from "./agent.ts";
import { textBatch, textSubmitBatch } from "./batch.ts";
import { imageGenerate } from "./image.ts";
import { textStream } from "./stream.ts";
import { textPrompt } from "./text.ts";
import { uploadRun } from "./upload.ts";
import type { AgentState } from "./agent.ts";

export class Client {
  provider: ProviderConfig;
  text: Text;
  image: Image;
  agent: Agent;
  upload: Upload;

  constructor(name: string, apiKey: string) {
    this.provider = { name, apiKey };
    this.text = new Text(this);
    this.image = new Image(this);
    this.agent = new Agent(this);
    this.upload = new Upload(this);
  }
}

export function newClient(name: string, apiKey: string): Client {
  return new Client(name, apiKey);
}

// === Per-provider factory functions ===
export function ai21(apiKey: string): Client { return new Client("ai21", apiKey); }
export function anthropic(apiKey: string): Client { return new Client("anthropic", apiKey); }
export function azure(apiKey: string): Client { return new Client("azure", apiKey); }
export function bedrock(apiKey: string): Client { return new Client("bedrock", apiKey); }
export function cerebras(apiKey: string): Client { return new Client("cerebras", apiKey); }
export function cohere(apiKey: string): Client { return new Client("cohere", apiKey); }
export function deepseek(apiKey: string): Client { return new Client("deepseek", apiKey); }
export function doubao(apiKey: string): Client { return new Client("doubao", apiKey); }
export function ernie(apiKey: string): Client { return new Client("ernie", apiKey); }
export function fireworks(apiKey: string): Client { return new Client("fireworks", apiKey); }
export function google(apiKey: string): Client { return new Client("google", apiKey); }
export function grok(apiKey: string): Client { return new Client("grok", apiKey); }
export function groq(apiKey: string): Client { return new Client("groq", apiKey); }
export function lmstudio(apiKey: string): Client { return new Client("lmstudio", apiKey); }
export function minimax(apiKey: string): Client { return new Client("minimax", apiKey); }
export function mistral(apiKey: string): Client { return new Client("mistral", apiKey); }
export function moonshot(apiKey: string): Client { return new Client("moonshot", apiKey); }
export function ollama(apiKey: string): Client { return new Client("ollama", apiKey); }
export function openai(apiKey: string): Client { return new Client("openai", apiKey); }
export function openrouter(apiKey: string): Client { return new Client("openrouter", apiKey); }
export function perplexity(apiKey: string): Client { return new Client("perplexity", apiKey); }
export function qwen(apiKey: string): Client { return new Client("qwen", apiKey); }
export function sambanova(apiKey: string): Client { return new Client("sambanova", apiKey); }
export function together(apiKey: string): Client { return new Client("together", apiKey); }
export function vllm(apiKey: string): Client { return new Client("vllm", apiKey); }
export function yi(apiKey: string): Client { return new Client("yi", apiKey); }
export function zhipu(apiKey: string): Client { return new Client("zhipu", apiKey); }

// === Text — ChatCompletion builder ===

export class Text {
  client: Client;
  _caching: boolean = false;
  _files: File[] = [];
  _frequencyPenalty?: number;
  _history: Message[] = [];
  _parts: Part[] = [];
  _maxTokens?: number;
  _middleware: MiddlewareFn[] = [];
  _model: string = "";
  _presencePenalty?: number;
  _reasoningEffort: string = "";
  _schema: string = "";
  _seed?: number;
  _stopSequences: string[] = [];
  _system: string = "";
  _temperature?: number;
  _thinkingBudget?: number;
  _topK?: number;
  _topP?: number;

  constructor(client: Client) { this.client = client; }

  caching(): Text { const out = clone(this); out._caching = true; return out; }
  file(id: string): Text { const out = clone(this); out._files = [...out._files, { id, uri: "", name: "", mimeType: "" }]; return out; }  // ordered
  frequencyPenalty(v: number): Text { const out = clone(this); out._frequencyPenalty = v; return out; }
  history(...msgs: Message[]): Text { const out = clone(this); out._history = msgs; return out; }
  image(mime: string, data: Uint8Array): Text { const out = clone(this); out._parts = [...out._parts, { image: { mimeType: mime, bytes: data } }]; return out; }  // ordered
  maxTokens(n: number): Text { const out = clone(this); out._maxTokens = n; return out; }
  middleware(...fns: MiddlewareFn[]): Text { const out = clone(this); out._middleware = [...out._middleware, ...fns]; return out; }
  model(name: string): Text { const out = clone(this); out._model = name; return out; }
  presencePenalty(v: number): Text { const out = clone(this); out._presencePenalty = v; return out; }
  reasoningEffort(level: string): Text { const out = clone(this); out._reasoningEffort = level; return out; }
  schema(s: string): Text { const out = clone(this); out._schema = s; return out; }
  seed(n: number): Text { const out = clone(this); out._seed = n; return out; }
  stopSequences(...seqs: string[]): Text { const out = clone(this); out._stopSequences = seqs; return out; }
  system(s: string): Text { const out = clone(this); out._system = s; return out; }
  temperature(t: number): Text { const out = clone(this); out._temperature = t; return out; }
  text(s: string): Text { const out = clone(this); out._parts = [...out._parts, { text: s }]; return out; }  // ordered
  thinkingBudget(n: number): Text { const out = clone(this); out._thinkingBudget = n; return out; }
  topK(n: number): Text { const out = clone(this); out._topK = n; return out; }
  topP(v: number): Text { const out = clone(this); out._topP = v; return out; }
  async prompt(msg: string): Promise<Response> {
    return textPrompt(this, msg);
  }
  stream(msg: string): AsyncIterable<string> {
    return textStream(this, msg);
  }
  async batch(...prompts: string[]): Promise<Response[]> {
    return textBatch(this, ...prompts);
  }
  async submitBatch(...prompts: string[]): Promise<BatchHandle> {
    return textSubmitBatch(this, ...prompts);
  }
}

// === Image — ImageGeneration builder ===

export class Image {
  client: Client;
  _aspectRatio: string = "";
  _caching: boolean = false;
  _parts: Part[] = [];
  _imageSize: string = "";
  _includeText: boolean = false;
  _middleware: MiddlewareFn[] = [];
  _model: string = "";

  constructor(client: Client) { this.client = client; }

  aspectRatio(r: string): Image { const out = clone(this); out._aspectRatio = r; return out; }
  caching(): Image { const out = clone(this); out._caching = true; return out; }
  image(mime: string, data: Uint8Array): Image { const out = clone(this); out._parts = [...out._parts, { image: { mimeType: mime, bytes: data } }]; return out; }  // ordered
  imageSize(s: string): Image { const out = clone(this); out._imageSize = s; return out; }
  includeText(): Image { const out = clone(this); out._includeText = true; return out; }
  middleware(...fns: MiddlewareFn[]): Image { const out = clone(this); out._middleware = [...out._middleware, ...fns]; return out; }
  model(name: string): Image { const out = clone(this); out._model = name; return out; }
  text(s: string): Image { const out = clone(this); out._parts = [...out._parts, { text: s }]; return out; }  // ordered
  async generate(msg: string): Promise<ImageResponse> {
    return imageGenerate(this, msg);
  }
}

// === Agent — ToolCalling builder ===

export class Agent {
  client: Client;
  _caching: boolean = false;
  _frequencyPenalty?: number;
  _maxTokens?: number;
  _middleware: MiddlewareFn[] = [];
  _model: string = "";
  _presencePenalty?: number;
  _reasoningEffort: string = "";
  _seed?: number;
  _stopSequences: string[] = [];
  _system: string = "";
  _temperature?: number;
  _thinkingBudget?: number;
  _tools: Tool[] = [];
  _topK?: number;
  _topP?: number;
  _state?: AgentState;

  constructor(client: Client) { this.client = client; }

  caching(): Agent { const out = clone(this); out._caching = true; out._state = undefined; return out; }
  frequencyPenalty(v: number): Agent { const out = clone(this); out._frequencyPenalty = v; out._state = undefined; return out; }
  maxTokens(n: number): Agent { const out = clone(this); out._maxTokens = n; out._state = undefined; return out; }
  middleware(...fns: MiddlewareFn[]): Agent { const out = clone(this); out._middleware = [...out._middleware, ...fns]; out._state = undefined; return out; }
  model(name: string): Agent { const out = clone(this); out._model = name; out._state = undefined; return out; }
  presencePenalty(v: number): Agent { const out = clone(this); out._presencePenalty = v; out._state = undefined; return out; }
  reasoningEffort(level: string): Agent { const out = clone(this); out._reasoningEffort = level; out._state = undefined; return out; }
  seed(n: number): Agent { const out = clone(this); out._seed = n; out._state = undefined; return out; }
  stopSequences(...seqs: string[]): Agent { const out = clone(this); out._stopSequences = seqs; out._state = undefined; return out; }
  system(s: string): Agent { const out = clone(this); out._system = s; out._state = undefined; return out; }
  temperature(t: number): Agent { const out = clone(this); out._temperature = t; out._state = undefined; return out; }
  thinkingBudget(n: number): Agent { const out = clone(this); out._thinkingBudget = n; out._state = undefined; return out; }
  tool(t: Tool): Agent { const out = clone(this); out._tools = [...out._tools, t]; out._state = undefined; return out; }
  topK(n: number): Agent { const out = clone(this); out._topK = n; out._state = undefined; return out; }
  topP(v: number): Agent { const out = clone(this); out._topP = v; out._state = undefined; return out; }
  async prompt(msg: string): Promise<Response> {
    return agentPrompt(this, msg);
  }
  reset(): void {
    return agentReset(this);
  }
}

// === Upload — FileUpload builder ===

export class Upload {
  client: Client;
  _bytes: Uint8Array = new Uint8Array(0);
  _filename: string = "";
  _middleware: MiddlewareFn[] = [];
  _mimeType: string = "";
  _path: string = "";

  constructor(client: Client) { this.client = client; }

  bytes(data: Uint8Array): Upload { const out = clone(this); out._bytes = data; return out; }
  filename(name: string): Upload { const out = clone(this); out._filename = name; return out; }
  middleware(...fns: MiddlewareFn[]): Upload { const out = clone(this); out._middleware = [...out._middleware, ...fns]; return out; }
  mimeType(mime: string): Upload { const out = clone(this); out._mimeType = mime; return out; }
  path(p: string): Upload { const out = clone(this); out._path = p; return out; }
  async run(): Promise<File> {
    return uploadRun(this);
  }
}

