// Code generated by codegen/generate.py; DO NOT EDIT.

// Catalogue builder classes (ADR-019). Chain methods are immutable; the
// HTTP-touching terminals delegate to hand-coded runtime in ../models.ts
// and ../providers.ts.

import type { Capability, Provider } from "../types.ts";
import type { LiveResult, ModelInfo } from "../structs.ts";
import type { ProviderInfo } from "../providers/provider_info.ts";
import type { Client } from "./builders.ts";
import {
  catalogueFilter,
  catalogueLookup,
  catalogueRunLive,
  catalogueRunList,
  catalogueRunGet,
} from "../models.ts";
import { catalogueProvidersList } from "../providers.ts";

/**
 * Models is the catalogue builder. Chain methods are immutable; list/get
 * walk the compiled-in slice synchronously, live(ctx) fans out HTTP
 * across configured providers, provider(p) returns ScopedModels.
 */
export class Models {
  /** @internal */ readonly client: Client;
  /** @internal */ readonly capFilter?: Capability;

  constructor(client: Client, capFilter?: Capability) {
    this.client = client;
    this.capFilter = capFilter;
  }

  /** Filter the catalogue to models whose ontology-derived capabilities
   *  array contains c. Composes with list / live / provider(p).list. */
  withCapability(c: Capability): Models {
    return new Models(this.client, c);
  }

  /** Scope the catalogue to a single provider; returns ScopedModels on
   *  which raw(), list(), and get(id) are reachable. */
  provider(p: Provider): ScopedModels {
    return new ScopedModels(this.client, p, this.capFilter);
  }

  /** Returns the compiled-in catalogue, filtered by withCapability when
   *  set. Sync, no IO. */
  list(): ModelInfo[] {
    return catalogueFilter(this.capFilter);
  }

  /** Returns a compiled-in model by id or undefined when no entry matches. */
  get(id: string): ModelInfo | undefined {
    return catalogueLookup(id);
  }

  /** Fan out HTTP across configured providers and return an aggregated
   *  LiveResult. withCapability composes post-fetch. */
  async live(): Promise<LiveResult> {
    return catalogueRunLive(this);
  }
}

/**
 * ScopedModels is the single-provider live-catalogue sub-builder.
 * Reached via Models.provider(p). raw() opts into populating
 * ModelInfo.raw per ADR-014.
 */
export class ScopedModels {
  /** @internal */ readonly client: Client;
  /** @internal */ readonly target: Provider;
  /** @internal */ readonly capFilter?: Capability;
  /** @internal */ readonly rawFlag: boolean;

  constructor(client: Client, target: Provider, capFilter?: Capability, rawFlag = false) {
    this.client = client;
    this.target = target;
    this.capFilter = capFilter;
    this.rawFlag = rawFlag;
  }

  raw(): ScopedModels {
    return new ScopedModels(this.client, this.target, this.capFilter, true);
  }

  async list(): Promise<ModelInfo[]> {
    return catalogueRunList(this);
  }

  async get(id: string): Promise<ModelInfo> {
    return catalogueRunGet(this, id);
  }
}

/**
 * Providers is the providers-namespace prototype. list() returns the
 * providers with both credentials configured and llm:hasModelsEndpoint
 * declared, as secret-free ProviderInfo (ADR-040 PSR-005). The static
 * roster of every supported provider is the `providers.list()` namespace.
 */
export class Providers {
  /** @internal */ readonly client: Client;

  constructor(client: Client) {
    this.client = client;
  }

  list(): ProviderInfo[] {
    return catalogueProvidersList(this.client);
  }
}
