// Code generated by codegen/generate.py; DO NOT EDIT.

import type { ImageData } from "./image.ts";
import type { Provider, Usage } from "./types.ts";

/**
 * BatchHandle is a value struct identifying a submitted batch. Cross-process resume works by persisting the three fields and reconstructing the handle.
 */
export interface BatchHandle {
  /**
   * id is the provider-assigned batch identifier returned by the create endpoint. Opaque to the SDK; round-tripped to the polling and result endpoints verbatim.
   */
  id: string;

  /**
   * provider is the Provider config used to submit the batch. Carried on the handle so Wait knows where to poll without re-parameterising the client.
   */
  provider: Provider;

  /**
   * raw is the ADR-014 opt-in: when true, every Response returned from Wait carries Response.raw set to the parsed per-item provider body. SubmitBatch propagates the chain's .raw() flag onto the handle; cross-process resume callers set the field directly.
   */
  raw?: boolean;
}

/**
 * ImageResponse is the universal image-generation response container returned by Image.Generate. Carries the decoded images, optional text captions/refusals, usage, and the same finish-reason / finish-message / raw fields the text-gen Response carries.
 */
export interface ImageResponse {
  /**
   * images are the decoded image payloads (mime type + raw bytes) returned by the provider. Empty when the provider blocks or refuses the request — inspect FinishReason / FinishMessage for the cause.
   */
  images: ImageData[];

  /**
   * text is the optional text response accompanying the images (captions, refusals, or model commentary). Populated only when the caller opted into mixed text + image output via the builder's IncludeText() chain method on providers that support it.
   */
  text: string;

  /**
   * usage holds token consumption metrics for the image-generation call. Google reports image-output tokens in usageMetadata.candidatesTokenCount; OpenAI Images API and Vertex Imagen do not return token counts so this stays zero on those providers.
   */
  usage: Usage;

  /**
   * finishReason is the provider stop signal. Examples per provider: Google STOP/IMAGE_OTHER/SAFETY/MAX_TOKENS; OpenAI Images API has no equivalent field (always empty); xAI Grok has no equivalent field (always empty); Vertex Imagen surfaces the RAI filter reason when content is blocked.
   */
  finishReason?: string;

  /**
   * finishMessage is the free-text provider explanation of the stop signal. Gemini populates this for non-success FinishReason values; other providers leave it empty. Use as the user-facing message when len(Images) == 0.
   */
  finishMessage?: string;

  /**
   * raw is the parsed provider response body, populated only when the caller opted in via the builder's .raw() chain method (ADR-014). Type-erased — consumers cast to a provider-shape type for fields the universal ImageResponse does not carry.
   */
  raw?: unknown;
}

/**
 * Response is the universal response container returned by text-generation terminals (Text.Prompt, Agent.Prompt). Five fields; all five are core (no per-capability augmentation).
 */
export interface Response {
  /**
   * text is the assistant's response text, extracted from the provider response body at the path declared by llm:hasResponseTextPath.
   */
  text: string;

  /**
   * usage holds token consumption metrics — input, output, cache_write, cache_read, and reasoning counts. Each dimension is populated from the provider-specific path declared in the ontology.
   */
  usage: Usage;

  /**
   * finishReason is the provider stop signal, passed through verbatim. Empty when the provider response carries no signal or the parser does not yet read this provider's location. Examples per provider: Google STOP/MAX_TOKENS/SAFETY/RECITATION; OpenAI stop/length/content_filter/tool_calls; Anthropic end_turn/max_tokens/stop_sequence/tool_use; xAI stop/length/content_filter.
   */
  finishReason?: string;

  /**
   * finishMessage is the provider-supplied free-text explanation of the stop signal. Populated by Google when present; OpenAI / Anthropic / xAI do not carry an equivalent field, so this stays empty for them.
   */
  finishMessage?: string;

  /**
   * raw is the parsed provider response body, populated only when the caller opted in via the typed builder's .raw() chain method (ADR-014). Type-erased — provider-specific fields (Anthropic citations, OpenAI logprobs, Google promptFeedback, ...) are not part of the universal Response shape; consumers cast to a provider-shape type once they know which provider they're talking to.
   */
  raw?: unknown;
}
