// Code generated by codegen/generate.py; DO NOT EDIT.

import type { Capability, Provider, Usage } from "./types.ts";

/**
 * BatchHandle is a value struct identifying a submitted batch. Cross-process resume works by persisting the three fields and reconstructing the handle.
 */
export interface BatchHandle {
  /**
   * id is the provider-assigned batch identifier returned by the create endpoint. Opaque to the SDK; round-tripped to the polling and result endpoints verbatim.
   */
  id: string;

  /**
   * provider is the Provider config used to submit the batch. Carried on the handle so Wait knows where to poll without re-parameterising the client.
   */
  provider: Provider;

  /**
   * raw is the ADR-014 opt-in: when true, every Response returned from Wait carries Response.raw set to the parsed per-item provider body. SubmitBatch propagates the chain's .raw() flag onto the handle; cross-process resume callers set the field directly.
   */
  raw?: boolean;
}

/**
 * File is a reference to an uploaded file. Returned by UploadFile and attached to subsequent text-generation requests via Request.Files.
 */
export interface File {
  /**
   * id is the provider-assigned file identifier returned by the upload endpoint. Empty when the provider returns only a URI.
   */
  id?: string;

  /**
   * uri is the provider-hosted URI of the uploaded file. Used in subsequent prompts to refer back to the file without re-uploading.
   */
  uri?: string;

  /**
   * mimeType is the IANA media type of the uploaded file as recorded by the provider (e.g., application/pdf, image/png). Carried so downstream prompts can route the file to the correct vision / document / audio path.
   */
  mimeType?: string;

  /**
   * name is the original filename supplied at upload time. Round-tripped through the provider so the caller can correlate the handle with the source artifact.
   */
  name?: string;
}

/**
 * ImageData is one decoded image payload returned in an ImageResponse. Same shape as MediaRef (mime type + raw bytes) but a distinct type so capability-specific return semantics stay typed: ImageResponse.images carries decoded outputs; MediaRef appears in input payloads and edit masks.
 */
export interface ImageData {
  /**
   * mimeType is the IANA media type of the returned image (image/png, image/jpeg, image/webp). Drives the file extension or data URI scheme the caller picks for storage.
   */
  mimeType: string;

  /**
   * bytes is the raw (not base64-encoded) decoded image payload. The SDK decodes provider wire format (base64, URL fetch) before returning so callers always see raw bytes.
   */
  bytes: Uint8Array;
}

/**
 * ImageResponse is the universal image-generation response container returned by Image.Generate. Carries the decoded images, optional text captions/refusals, usage, and the same finish-reason / finish-message / raw fields the text-gen Response carries.
 */
export interface ImageResponse {
  /**
   * images are the decoded image payloads (mime type + raw bytes) returned by the provider. Empty when the provider blocks or refuses the request — inspect FinishReason / FinishMessage for the cause.
   */
  images: ImageData[];

  /**
   * text is the optional text response accompanying the images (captions, refusals, or model commentary). Populated only when the caller opted into mixed text + image output via the builder's IncludeText() chain method on providers that support it.
   */
  text: string;

  /**
   * usage holds token consumption metrics for the image-generation call. Google reports image-output tokens in usageMetadata.candidatesTokenCount; OpenAI Images API and Vertex Imagen do not return token counts so this stays zero on those providers.
   */
  usage: Usage;

  /**
   * finishReason is the provider stop signal. Examples per provider: Google STOP/IMAGE_OTHER/SAFETY/MAX_TOKENS; OpenAI Images API has no equivalent field (always empty); xAI Grok has no equivalent field (always empty); Vertex Imagen surfaces the RAI filter reason when content is blocked.
   */
  finishReason?: string;

  /**
   * finishMessage is the free-text provider explanation of the stop signal. Gemini populates this for non-success FinishReason values; other providers leave it empty. Use as the user-facing message when len(Images) == 0.
   */
  finishMessage?: string;

  /**
   * raw is the parsed provider response body, populated only when the caller opted in via the builder's .raw() chain method (ADR-014). Type-erased — consumers cast to a provider-shape type for fields the universal ImageResponse does not carry.
   */
  raw?: unknown;
}

/**
 * LiveResult is returned by c.Models.Live(ctx) — the aggregated cross-provider live result. Partial success is the documented normal case: per-provider failures land in Errors while everything that succeeded lands in Models.
 */
export interface LiveResult {
  /**
   * models are the ModelInfo records that returned successfully across configured providers. Sorted by (provider name, id) for deterministic ordering across calls.
   */
  models: ModelInfo[];

  /**
   * errors is the per-provider failure map. Empty when every configured provider succeeded. Keyed by Provider; each value carries the per-provider error sentinel (ErrModelsScope / ErrModelsUnavailable / ErrModelsNotSupported).
   */
  errors: Record<string, string>;
}

/**
 * MediaRef is an inline media payload (mime type + raw bytes). Reused by every Part variant that carries non-text content, and by image-generation knobs like Mask that pass through a single binary blob.
 */
export interface MediaRef {
  /**
   * mimeType is the IANA media type of the bytes payload (image/png, image/jpeg, audio/wav, ...). Drives both the wire encoding (base64 mime prefix on data URIs) and provider routing on multimodal endpoints.
   */
  mimeType: string;

  /**
   * bytes is the raw (not base64-encoded) media payload. The transform layer base64-encodes at wire time per provider; callers always pass raw bytes.
   */
  bytes: Uint8Array;
}

/**
 * Message is a single turn in a multi-turn conversation. Role identifies the speaker; content carries the turn's text. Multimodal content (a Part list) is deferred to a later slice; today content is the raw string.
 */
export interface Message {
  /**
   * role is the speaker identifier. Conventionally "user" or "assistant"; provider transforms may map to other roles (Bedrock's "USER"/"ASSISTANT", Google's "user"/"model").
   */
  role: string;

  /**
   * content is the turn's text. Multimodal content (a list of Parts) is deferred to a follow-up slice; today this is the concatenated text of the turn.
   */
  content: string;
}

/**
 * ModelInfo is the universal model descriptor returned by c.Models methods (compiled-in and live). Capabilities is always ontology-derived — never from wire data; wire fills the metadata fields when present.
 */
export interface ModelInfo {
  /**
   * id is the provider-scoped model identifier (e.g. claude-opus-4-7, gpt-5, gemini-2.5-flash). Round-tripped to provider endpoints verbatim.
   */
  id: string;

  /**
   * provider is the Provider value that exposes this model. Used by Models.Provider(m.Provider).Get(ctx, m.ID) to round-trip back to live data when needed.
   */
  provider: Provider;

  /**
   * capabilities is the SDK's understanding of what this model supports — chat completion, image generation, tool calling, etc. Always populated from the ontology, never from wire data. Empty (nil) for live IDs the SDK does not recognise.
   */
  capabilities: Capability[];

  /**
   * displayName is the human-readable name when the provider supplies one (Anthropic display_name, Google displayName). Empty when the provider's wire shape does not carry one or for compiled-in entries.
   */
  displayName?: string;

  /**
   * description is the provider's free-text description (Google description). Empty for providers that do not publish a description field and for compiled-in entries.
   */
  description?: string;

  /**
   * contextWindow is the maximum input token count when published (Anthropic max_input_tokens, Google inputTokenLimit). Zero when the provider does not publish it (OpenAI-shape cohort) or for compiled-in entries without a curated value.
   */
  contextWindow?: number;

  /**
   * maxOutput is the maximum output token count when published (Anthropic max_tokens, Google outputTokenLimit). Zero when the provider does not publish it or for compiled-in entries.
   */
  maxOutput?: number;

  /**
   * created is the Unix-timestamp creation time when the provider publishes one (Anthropic created_at parsed to Unix, OpenAI created). Zero for compiled-in entries and providers that do not publish it.
   */
  created?: number;

  /**
   * raw is the parsed provider-native record for this model, populated only when the caller opted in via the builder's .Raw() chain method (ADR-014). Type-erased — consumers cast to a provider-shape type for fields the universal ModelInfo does not carry (Anthropic capability matrix, Google supportedGenerationMethods, etc.).
   */
  raw?: unknown;
}

/**
 * Response is the universal response container returned by text-generation terminals (Text.Prompt, Agent.Prompt). Five fields; all five are core (no per-capability augmentation).
 */
export interface Response {
  /**
   * text is the assistant's response text, extracted from the provider response body at the path declared by llm:hasResponseTextPath.
   */
  text: string;

  /**
   * usage holds token consumption metrics — input, output, cache_write, cache_read, and reasoning counts. Each dimension is populated from the provider-specific path declared in the ontology.
   */
  usage: Usage;

  /**
   * finishReason is the provider stop signal, passed through verbatim. Empty when the provider response carries no signal or the parser does not yet read this provider's location. Examples per provider: Google STOP/MAX_TOKENS/SAFETY/RECITATION; OpenAI stop/length/content_filter/tool_calls; Anthropic end_turn/max_tokens/stop_sequence/tool_use; xAI stop/length/content_filter.
   */
  finishReason?: string;

  /**
   * finishMessage is the provider-supplied free-text explanation of the stop signal. Populated by Google when present; OpenAI / Anthropic / xAI do not carry an equivalent field, so this stays empty for them.
   */
  finishMessage?: string;

  /**
   * raw is the parsed provider response body, populated only when the caller opted in via the typed builder's .raw() chain method (ADR-014). Type-erased — provider-specific fields (Anthropic citations, OpenAI logprobs, Google promptFeedback, ...) are not part of the universal Response shape; consumers cast to a provider-shape type once they know which provider they're talking to.
   */
  raw?: unknown;
}
